### ISSUE TITLE
能请教个问题吗

### ISSUE THREAD

**Issue by lk0606** [hujiulong/echarts-threejs-earth#1]
怎样画经纬线，
.wireframe : boolean
如何定义这个网格呢，只显示一些，或者密度增加
或者3D地球弄成点状？

**Comment by hujiulong** [comment]
@lk0606  如果用wireframe的话，调整下[SphereBufferGeometry](https://threejs.org/docs/index.html#api/en/geometries/SphereBufferGeometry)的参数可以达到这个效果，但是这样可能会让地球看起来不那么圆。可以试试保持地球不变，在地球上套一个wireframe为true的球，半径稍微大一点点

**Comment by lk0606** [comment]
不是啊亲，我是想要两个效果，
1. 地球是网状的或者点状的
2. 在增加一层地球的纬线，或者经线
方便加个微信吗，
可以聊聊three方面
